name: linux

on:
  push:
  pull_request:
  release:
    types: published

jobs:

  build:
    name: ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x64 ]
        config: [ debug, release ]

    steps:

    - name: Setup python environment
      run: |
        pip install PyYAML

    - name: Check out code
      uses: actions/checkout@v3

    - name: Fetch dependencies
      run: |
        ./fetch_deps

    - name: Fetch gn and ninja
      run: |
        python build/fetch_binaries.py

    - name: Compile
      run: |
        build/bin/gn gen out/${{ matrix.config }}_${{ matrix.arch }} --args="target_cpu=\"${{ matrix.arch }}\" is_debug=${{ matrix.config == 'debug' }}"
        build/bin/ninja -C out/${{ matrix.config }}_${{ matrix.arch }}

    - name: Test
      run: |
        python sample/test.py out/${{ matrix.config }}_${{ matrix.arch }}

    - name: Make package
      if: runner.os == 'Linux'
      run: |
        tar zcvf out/${{ matrix.config }}_${{ matrix.arch }}/zlibwrap_linux_${{ matrix.arch }}.tar.gz \
          -C out/${{ matrix.config }}_${{ matrix.arch }} \
          libzlibwrap.a \
          libzlibwrapd.so \
          zip \
          unzip

    - name: Upload Release on push tag
      if: startsWith(github.ref, 'refs/tags/v') && matrix.config == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/${{ matrix.config }}_${{ matrix.arch }}/zlibwrap_linux_${{ matrix.arch }}.tar.gz
